PazYSalvoAPP/PazYSalvoAPP.WebApp/Models/ViewModels/EstadoViewModel.cs
using PazYSalvoAPP.Models;
using System.ComponentModel.DataAnnotations;

namespace PazYSalvoAPP.WebApp.Models.ViewModels
{
    public class EstadoViewModel
    {
        public int Id { get; set; }

        public string? Nombre { get; set; }

        public string? Descripcion { get; set; }


    }
}

PazYSalvoAPP/PazYSalvoAPP.WebApp/Controllers/Estados/EstadoController.cs
using Microsoft.AspNetCore.Mvc;
using PazYSalvoAPP.Business.Services;
using PazYSalvoAPP.Models;
using PazYSalvoAPP.WebApp.Models.ViewModels;

namespace PazYSalvoAPP.WebApp.Controllers.Estados
{
    public class EstadoController : Controller
    {
        private readonly IEstadoService _estadoService;
        public EstadoController(IEstadoService estadoService)
        {
            _estadoService = estadoService;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> ListarEstados()
        {
            IQueryable<Estado>? consultaDeEstados = await _estadoService.LeerTodos();

            List<EstadoViewModel> listadoDeEstados = consultaDeEstados.Select(e => new EstadoViewModel
            {
                Id = e.Id,
                Nombre = e.Nombre,
                Descripcion = e.Descripcion,

            }).ToList();

            return PartialView("_ListadoDeEstado",
                              listadoDeEstados);
        }
        //[HttpPost] // *
        //public async Task<IActionResult> AgregarFacturas([FromBody] FacturaViewModel model)
        //{
        //    Estado estado = new estado()
        //    {

        //        Nombre = e.Nombre,
        //        Descripcion = e.Descripcion,
        //    };

        //    bool response = await _estadoService.Insertar(estado);

        //    return RedirectToAction("Index");

        //}

        //[HttpPost]
        //public async Task<IActionResult> ActualizarFacturas([FromBody] FacturaViewModel model)
        //{
        //    Factura factura = new Factura()
        //    {


        //    };

        //    bool response = await _estadoService.Actualizar(factura);

        //    return StatusCode(StatusCodes.Status200OK,
        //                      new { valor = response });

        //}
    }
}

PazYSalvoAPP/PazYSalvoAPP.WebApp/Views/Estado/Index.cshtml
@*@model IEnumerable<PazYSalvoAPP.WebApp.Models.ViewModels.EstadoViewModel>*@
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="container">
    <h2>Administrador de facturas</h2>
    <p class="descripcion">
        Este administrador nos permite visualizar y gestionar todo lo referente a estados de las facturas del negocio.
    </p>

    <div class="opciones-container">
        <a class="btn btn-primary btn-sm" id="btnVerEstados">Ver Estados</a>
        <a class="btn btn-success btn-sm visually-hidden" id="btnNuevoEstado">Nuevo Estado</a>
    </div>

    <div id="tblListaDeEstados">
    </div>
</div>

@*MODAL*@
<div class="modal-container">
    <div class="modal" id="modal" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="tituloModal"></h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="post" id="frmModalEstado">
                    <div class="modal-body">

                        <div class="form-group">

                            <input type="hidden" class="form-control" id="IdValor">
                        </div>

                        <div class="form-group">
                            <label for="SaldoValor">Nombre</label>
                            <input type="text" class="form-control" id="SaldoValor">
                        </div>

                        <div class="form-group">
                            <label for="ClienteValor">Descripción</label>
                            <input type="text" class="form-control" id="ClienteValor">
                        </div>

                        

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                        <button type="submit" class="btn btn-primary" id="btnActualizarFactura">Agregar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>
@*FIN MODAL*@


@section Scripts {
    <script>
        $(document).ready(function () {
            
            // btnVerEstados
            $("#btnVerEstados").click(async function () {
                const url = "@Url.Action("ListarEstados", "Estado")";
                const response = await $.ajax({
                    url: url,
                    method: "GET",
                    dataType: "html"
                });

                $("#tblListaDeEstados").html(response);
                $("#btnVerEstados").hide();
                $("#btnNuevoEstado").removeClass("visually-hidden"); // visually-hidden

            });

            // mostrar modal nuevo estado
            $("#btnNuevoEstado").click(function () {
                mostrarModal();


            });

        });

        function mostrarModal() {

            // Actualiza el título de la modal
            $("#tituloModal").text("Estado");

            // Limpia los campos del formulario
            $("#frmModalEstado").trigger("reset");

            // Muestra la modal
            $("#modal").modal("show");

        }
    </script>
}

PazYSalvoAPP/PazYSalvoAPP.WebApp/Views/Estado/_ListadoDeEstado.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<hr />
<div class="container">

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Descripción</th>
                <th>Opciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {

                <tr>
                    <th>@item.Nombre</th>
                    <td>@item.Descripcion</td>
                   
                    <td>
                        <a class="btn btn-info btn-sm">Editar</a>
                        <a class="btn btn-warning btn-sm disabled">Eliminar</a>
                    </td>
                </tr>
            }


        </tbody>
    </table>
</div>